# Maintainer: Patrik Cihal
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=stellar-bit-client-bin
pkgver=0.1.0
pkgrel=1
pkgdesc="Stellar Bit Client"
url="none"
license=("MIT")
arch=("x86_64")
provides=("stellar-bit-client")
conflicts=("stellar-bit-client")
source=("https://github.com/stellar-bit/client-basic/releases/download/v$pkgver/stellar-bit-client-$pkgver-x86_64.tar.gz")
sha256sums=("e7968a98e9ad35500665223f36be00f30a5b3898dd9db0f6cb44206366e7ba9a")

package() {
    install -Dm755 stellar-bit-client -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
    cp -r ../../assets "$pkgdir/usr/share/$pkgname/assets"
}
